### ISSUE TITLE
Topics for discussion at the CTA Fall Forum CMAF-IF Workshop 2021

### ISSUE THREAD

**Issue by ablasgen** [cta-wave/cmaf-if#7]
The CMAF Industry Forum will hold a virtual meeting on Tuesday, September 21st from 07:00-09:00 am PT. 

Use this issue tracker to contribute discussion items. These will be collated by the CMAF-IF Chair before the meeting and converted in to a presentation deck to drive the agenda for the day. For each item, please suggest a title, and provide some background text as well as the decision to made or call-to-action.

**Comment by johnsim** [comment]
It would be ideal to get preliminary feedback on the new DASH-HLS interop specification prior to the CMAF IF virtual meeting. Review of this feedback would be a good agenda item.

**Comment by johnsim** [comment]
Status of new published CMAF media profiles, in MPEG and elsewhere.

**Comment by johnsim** [comment]
**External Evangelism of WAVE Specs**, Discussed in the WAVE Meeting 9/20/2021, Suggested by: Zack Cava, and discussed as being a topic for the CMAF Industry Forum session: 

Common routes vs specification-specific.

Do we want to establish some general operating procedures to
ensure we are making our specs well known in the industry and
getting feedback for subsequent editions?

How do we identify and track industry groups / areas that align with
a particular specification?
